version: '3.8'
services:
  mysql-db:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: persondb
    ports:
      - '3307:3306'
  application:
    build:
      context: .
      dockerfile: Dockerfile
    image: person-service:1.0
    depends_on:
      - mysql-db
    ports:
      - '7070:7070'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-db:3306/persondb'
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password